# Generated by Django 3.1.6 on 2021-02-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_player_total_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_info',
            field=models.CharField(default='No info provided.', max_length=2000),
        ),
    ]
